apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: predicted-cpu-exporter
  labels: {app: predicted-cpu-exporter}
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata: {labels: {app: predicted-cpu-exporter}}
    spec:
      containers:
      - name: predicted-cpu-exporter
        image: docker.io/cptplaneta/predicted-cpu-exporter:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: predicted-cpu-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  selector: 
    app: tracking
  ports:
  - port: 9999
    targetPort: 8080
