apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: predicted-cpu-exporter
  labels: 
    app: predicted-cpu-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata: 
      labels: 
        app: predicted-cpu-exporter
    spec:
      containers:
      - name: predicted-cpu-exporter
        image: docker.io/cptplaneta/predicted-cpu-exporter:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        args: ["--listen-address=:8080", "--prometheus-url=http://kube-prometheus:9090"]

---
apiVersion: v1
kind: Service
metadata:
  name: predicted-cpu-exporter
  namespace: monitoring
  labels: 
    app: predicted-cpu-exporter
spec:
  type: ClusterIP
  selector: 
    app: predicted-cpu-exporter
  ports:
  - name: metrics
    port: 9999
    targetPort: 8080
