apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: predicted-cpu-exporter
  namespace: monitoring
  labels:
    app: predicted-cpu-exporter
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: predicted-cpu-exporter
  endpoints:
  - port: metrics
    interval: 10s       
